version: "3"

services:
  cv:
    build: .
    volumes:
      - ./src:/root/src
      - ./datasets:/root/datasets
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
    tty: true
    privileged: true
    network_mode: "host"
